

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 800141
 */
public class WarriorCat extends javax.swing.JFrame {
        // arraylists
        String[] fName;
        String[] eName;
        String[] peltC;
        String[] eyeC;
        String[] personality;
        String[] history;
        String[] clan;
     
        
        // variables used for random number generators
        int f;
        int e;
        int pc;
        int ec;
        int p;
        int h;
        int c;
        // output variable
        String o;
        String gender;
    /**
     * Creates new form WarriorCat
     */
    public WarriorCat() {
        // set size of arraylists
        fName = new String[15];
        eName = new String[15];
        peltC = new String[10];
        eyeC = new String[3];
        personality = new String[8];
        history = new String[5];
        clan = new String[5];
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputBox = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 204, 153));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel1.setText("What Gender (Male/Female) do you associate with?");
        jLabel1.setOpaque(true);

        inputBox.setBackground(new java.awt.Color(255, 204, 153));

        generate.setBackground(new java.awt.Color(255, 204, 153));
        generate.setText("Generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d95yas0-52914c3f-8087-4ce3-b595-9cf353ec4171.png"))); // NOI18N

        outputBox.setBackground(new java.awt.Color(255, 204, 153));
        outputBox.setColumns(20);
        outputBox.setRows(5);
        jScrollPane1.setViewportView(outputBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generate)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // arraylists of possibilities
    private void initfName(){
        fName[0] = "Fire";
        fName[1] = "Blue";
        fName[2] = "Tiger";
        fName[3] = "Leopard";
        fName[4] = "Cloud";
        fName[5] = "Raven";
        fName[6] = "Mouse";
        fName[7] = "Dusk";
        fName[8] = "Hawk";
        fName[9] = "Bramble";
        fName[10] = "Sand";
        fName[11] = "Silver";
        fName[12] = "Frost";
        fName[13] = "Swift";
        fName[14] = "Long";
    }
    private void initeName(){
        eName[0] = "kit";
        eName[1] = "paw";
        eName[2] = "star";
        eName[3] = "claw";
        eName[4] = "fur";
        eName[5] = "stream";
        eName[6] = "feather";
        eName[7] = "pelt";
        eName[8] = "storm";
        eName[9] = "tail";
        eName[10] = "fang";
        eName[11] = "stripe";
        eName[12] = "heart";
        eName[13] = "wing";
        eName[14] = "flower";
    }
    private void  initpeltC(){
        peltC[0] = "black";
        peltC[1] = "white";
        peltC[2] = "brown";
        peltC[3] = "grey";
        peltC[4] = "orange";
        peltC[5] = "calico";
        peltC[6] = "cream";
        peltC[7] = "black and white";
        peltC[8] = "cream and black";
        peltC[9] = "grey and black";
    }
    private void initeyeC(){
        eyeC[0] = "yellow";
        eyeC[1] = "blue";
        eyeC[2] = "blind";
    }
    private void initpersonality(){
        personality[0] = "jealous, liar, selfish, dominate";
        personality[1] = "friendly, helpful, trustworthy, kind";
        personality[2] = "gentle, shy, quiet";
        personality[3] = "wise, observant, loyal, patient";
        personality[4] = "sadistic, sly, hateful";
        personality[5] = "elegant, lovable, caring, passionate";
        personality[6] = "snarky, playful, humorous, talkative";
        personality[7] = "romantic, strong, charming, cheerful";
    }
    private void inithistory(){
        history[0] = "As a kit you dreamed of becoming the leader of your clan" +
                "\n You trained endlessly for many moons when on day your best frend" +
                "\n was chosen to become the next leader. You planned revenge against" +
                "\n against your entire clan.";
        history[1] = "Alongside your twin, the two of you trained to be the best warriors" +
                "\n you could be. Everything was going well with your life, until one day" +
                "\n you were attacked by a badger. You survived the attack, however you were"+
                "\n gravely injured. Your injury destroyed any chance you had at becoming a" +
                "\n warrior";
        history[2] = "You are the medicine cat. You play a major role in your clan, healing" +
                "\n those who are injured on the battlefield, or ill. Your knowledge of herbs " +
                "\n is respected by all of your fellow cats";
        history[3] = "You've fought ofr every scrap you could get your paws on. Life has thrown every" +
                "\n challenge your way, and you've defeated each one. You know nothing in life is free." +
                "\n You fight for your right to live and don't let anyone say otherwise";
        history[4] = "You were born during the great journey, and made a long track to the new territories." +
                "\n During the trip, you ran into a lot of bad things. Your luck doesn't seem to favor you" +
                "\n, however you made it threw it. You learned a lot on the way and became close to the tribe" +
                "\n of Rushing Water";
    }
    private void initclan(){
        clan[0] = "Riverclan";
        clan[1] = "Thunderclan";
        clan[2] = "Shadowclan";
        clan[3] = "Windclan";
        clan[4] = "outsider";
    }
    
    
    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        // initiate arraylists
        initfName();
        initeName();
        initpeltC();
        initeyeC();
        initpersonality();
        inithistory();
        initclan();
        // get info from user
        gender = inputBox.getText();
        
        // random numbers
        f = (int) (Math.random()* 15); 
        e = (int) (Math.random()* 15);
        pc = (int) (Math.random()* 10);
        ec = (int) (Math.random()* 3);
        p = (int) (Math.random()* 8);
        h = (int) (Math.random()* 5);
        c = (int) (Math.random()* 5);
        
        // output
        o = " Name:" + " " + fName[f] + eName[e] +
            "\n Gender:" + " " + gender +
            "\n Clan:" + " " + clan[c] +
            "\n Personality:" + " " + personality[p] +
            "\n Appearence:" + " "+ peltC[pc] + " " + "with" + " "+ eyeC[ec] + " " + "eyes" +
            "\n Backstory:" + " " + history[h];
        
        outputBox.setText(o);
        
        // pictures
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarriorCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarriorCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarriorCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarriorCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarriorCat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generate;
    private javax.swing.JTextField inputBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputBox;
    // End of variables declaration//GEN-END:variables
}
